### PR TITLE
Migrate spec build to python 3.11

### PR DESCRIPTION
**Pull request by smarlowucf**
- Update python version for ci testing

### CODE REVIEW

**Comment by smarlowucf** [comment]
Tests fixed in https://github.com/SUSE-Enceladus/aliyun-img-utils/pull/45

**Review by apozsuse — APPROVED** [review]
LGTM

**Comment by arozyev** [comment]
looks good, only confused about that why we're keeping python 3.8, 3.9, 3.10? Since we're not going to check/use fully on those versions publishing it for that python releases feels little opportunistic, users can open a bug if something won't work.

**Comment by rjschwei** [comment]
LGTM

**Pull request merged**
